#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include "exti_register_map.hpp"

using namespace stm32::exti;
using namespace testing;

class MockExtiRegisterMap : public IExtiRegisterMap
{
public:

	// IMR Fields
	MOCK_METHOD(InterruptMask, get_IMR_MR0, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR1, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR2, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR3, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR4, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR5, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR6, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR7, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR8, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR9, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR10, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR11, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR12, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR13, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR14, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR15, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR16, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR17, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR18, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR19, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR20, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR21, (), (const, override));
	MOCK_METHOD(InterruptMask, get_IMR_MR22, (), (const, override));
	MOCK_METHOD(void, set_IMR_MR0, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR1, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR2, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR3, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR4, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR5, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR6, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR7, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR8, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR9, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR10, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR11, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR12, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR13, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR14, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR15, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR16, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR17, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR18, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR19, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR20, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR21, (InterruptMask), (override));
	MOCK_METHOD(void, set_IMR_MR22, (InterruptMask), (override));

	// EMR Fields
	MOCK_METHOD(InterruptMask, get_EMR_MR0, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR1, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR2, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR3, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR4, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR5, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR6, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR7, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR8, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR9, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR10, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR11, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR12, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR13, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR14, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR15, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR16, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR17, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR18, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR19, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR20, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR21, (), (const, override));
	MOCK_METHOD(InterruptMask, get_EMR_MR22, (), (const, override));
	MOCK_METHOD(void, set_EMR_MR0, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR1, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR2, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR3, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR4, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR5, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR6, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR7, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR8, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR9, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR10, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR11, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR12, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR13, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR14, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR15, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR16, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR17, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR18, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR19, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR20, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR21, (InterruptMask), (override));
	MOCK_METHOD(void, set_EMR_MR22, (InterruptMask), (override));

	// RTSR Fields
	MOCK_METHOD(EnableFlag, get_RTSR_TR0, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR1, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR2, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR3, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR4, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR5, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR6, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR7, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR8, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR9, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR10, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR11, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR12, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR13, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR14, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR15, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR16, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR17, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR18, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR19, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR20, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR21, (), (const, override));
	MOCK_METHOD(EnableFlag, get_RTSR_TR22, (), (const, override));
	MOCK_METHOD(void, set_RTSR_TR0, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR1, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR2, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR3, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR4, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR5, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR6, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR7, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR8, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR9, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR10, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR11, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR12, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR13, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR14, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR15, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR16, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR17, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR18, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR19, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR20, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR21, (EnableFlag), (override));
	MOCK_METHOD(void, set_RTSR_TR22, (EnableFlag), (override));

	// FTSR Fields
	MOCK_METHOD(EnableFlag, get_FTSR_TR0, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR1, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR2, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR3, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR4, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR5, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR6, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR7, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR8, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR9, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR10, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR11, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR12, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR13, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR14, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR15, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR16, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR17, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR18, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR19, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR20, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR21, (), (const, override));
	MOCK_METHOD(EnableFlag, get_FTSR_TR22, (), (const, override));
	MOCK_METHOD(void, set_FTSR_TR0, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR1, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR2, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR3, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR4, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR5, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR6, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR7, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR8, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR9, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR10, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR11, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR12, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR13, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR14, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR15, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR16, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR17, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR18, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR19, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR20, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR21, (EnableFlag), (override));
	MOCK_METHOD(void, set_FTSR_TR22, (EnableFlag), (override));

	// SWIER Fields
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER0, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER1, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER2, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER3, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER4, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER5, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER6, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER7, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER8, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER9, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER10, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER11, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER12, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER13, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER14, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER15, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER16, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER17, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER18, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER19, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER20, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER21, (), (const, override));
	MOCK_METHOD(SoftwareInterrupt, get_SWIER_SWIER22, (), (const, override));
	MOCK_METHOD(void, set_SWIER_SWIER0, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER1, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER2, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER3, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER4, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER5, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER6, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER7, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER8, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER9, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER10, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER11, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER12, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER13, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER14, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER15, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER16, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER17, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER18, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER19, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER20, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER21, (SoftwareInterrupt), (override));
	MOCK_METHOD(void, set_SWIER_SWIER22, (SoftwareInterrupt), (override));

	// PR Fields
	MOCK_METHOD(PendingBit, get_PR_PR0, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR1, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR2, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR3, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR4, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR5, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR6, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR7, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR8, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR9, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR10, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR11, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR12, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR13, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR14, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR15, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR16, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR17, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR18, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR19, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR20, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR21, (), (const, override));
	MOCK_METHOD(PendingBit, get_PR_PR22, (), (const, override));
	MOCK_METHOD(void, set_PR_PR0, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR1, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR2, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR3, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR4, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR5, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR6, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR7, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR8, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR9, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR10, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR11, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR12, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR13, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR14, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR15, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR16, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR17, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR18, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR19, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR20, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR21, (PendingBit), (override));
	MOCK_METHOD(void, set_PR_PR22, (PendingBit), (override));
};

