#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include "gpio_register_map.hpp"

using namespace stm32::gpio;
using namespace testing;

class MockGpioRegisterMap : public IGpioRegisterMap
{
public:

	// MODER Fields
	MOCK_METHOD(Mode, get_MODER_MODER0, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER1, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER2, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER3, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER4, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER5, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER6, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER7, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER8, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER9, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER10, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER11, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER12, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER13, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER14, (), (const, override));
	MOCK_METHOD(Mode, get_MODER_MODER15, (), (const, override));
	MOCK_METHOD(void, set_MODER_MODER0, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER1, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER2, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER3, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER4, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER5, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER6, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER7, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER8, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER9, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER10, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER11, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER12, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER13, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER14, (Mode), (override));
	MOCK_METHOD(void, set_MODER_MODER15, (Mode), (override));

	// OTYPER Fields
	MOCK_METHOD(OutputType, get_OTYPER_OT0, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT1, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT2, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT3, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT4, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT5, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT6, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT7, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT8, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT9, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT10, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT11, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT12, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT13, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT14, (), (const, override));
	MOCK_METHOD(OutputType, get_OTYPER_OT15, (), (const, override));
	MOCK_METHOD(void, set_OTYPER_OT0, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT1, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT2, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT3, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT4, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT5, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT6, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT7, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT8, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT9, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT10, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT11, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT12, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT13, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT14, (OutputType), (override));
	MOCK_METHOD(void, set_OTYPER_OT15, (OutputType), (override));

	// OSPEEDR Fields
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR0, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR1, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR2, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR3, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR4, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR5, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR6, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR7, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR8, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR9, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR10, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR11, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR12, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR13, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR14, (), (const, override));
	MOCK_METHOD(Speed, get_OSPEEDR_OSPEEDR15, (), (const, override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR0, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR1, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR2, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR3, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR4, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR5, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR6, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR7, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR8, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR9, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR10, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR11, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR12, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR13, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR14, (Speed), (override));
	MOCK_METHOD(void, set_OSPEEDR_OSPEEDR15, (Speed), (override));

	// PUPDR Fields
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR0, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR1, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR2, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR3, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR4, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR5, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR6, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR7, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR8, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR9, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR10, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR11, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR12, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR13, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR14, (), (const, override));
	MOCK_METHOD(PullUpPullDown, get_PUPDR_PUPDR15, (), (const, override));
	MOCK_METHOD(void, set_PUPDR_PUPDR0, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR1, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR2, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR3, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR4, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR5, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR6, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR7, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR8, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR9, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR10, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR11, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR12, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR13, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR14, (PullUpPullDown), (override));
	MOCK_METHOD(void, set_PUPDR_PUPDR15, (PullUpPullDown), (override));

	// IDR Fields
	MOCK_METHOD(uint32_t, get_IDR_IDR0, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR1, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR2, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR3, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR4, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR5, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR6, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR7, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR8, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR9, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR10, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR11, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR12, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR13, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR14, (), (const, override));
	MOCK_METHOD(uint32_t, get_IDR_IDR15, (), (const, override));

	// ODR Fields
	MOCK_METHOD(uint32_t, get_ODR_ODR0, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR1, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR2, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR3, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR4, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR5, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR6, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR7, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR8, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR9, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR10, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR11, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR12, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR13, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR14, (), (const, override));
	MOCK_METHOD(uint32_t, get_ODR_ODR15, (), (const, override));
	MOCK_METHOD(void, set_ODR_ODR0, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR1, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR2, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR3, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR4, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR5, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR6, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR7, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR8, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR9, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR10, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR11, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR12, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR13, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR14, (uint32_t), (override));
	MOCK_METHOD(void, set_ODR_ODR15, (uint32_t), (override));

	// BSRR Fields
	MOCK_METHOD(void, set_BSRR_BS0, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS1, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS2, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS3, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS4, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS5, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS6, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS7, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS8, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS9, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS10, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS11, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS12, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS13, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS14, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BS15, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR0, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR1, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR2, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR3, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR4, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR5, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR6, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR7, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR8, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR9, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR10, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR11, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR12, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR13, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR14, (uint32_t), (override));
	MOCK_METHOD(void, set_BSRR_BR15, (uint32_t), (override));

	// LCKR Fields
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK0, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK1, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK2, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK3, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK4, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK5, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK6, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK7, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK8, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK9, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK10, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK11, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK12, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK13, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK14, (), (const, override));
	MOCK_METHOD(PortConfigurationLock, get_LCKR_LCK15, (), (const, override));
	MOCK_METHOD(PortConfigurationLockKey, get_LCKR_LCKK, (), (const, override));
	MOCK_METHOD(void, set_LCKR_LCK0, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK1, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK2, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK3, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK4, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK5, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK6, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK7, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK8, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK9, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK10, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK11, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK12, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK13, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK14, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCK15, (PortConfigurationLock), (override));
	MOCK_METHOD(void, set_LCKR_LCKK, (PortConfigurationLockKey), (override));

	// AFRL Fields
	MOCK_METHOD(AlternateFunction, get_AFRL_AFRL0, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRL_AFRL1, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRL_AFRL2, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRL_AFRL3, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRL_AFRL4, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRL_AFRL5, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRL_AFRL6, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRL_AFRL7, (), (const, override));
	MOCK_METHOD(void, set_AFRL_AFRL0, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRL_AFRL1, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRL_AFRL2, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRL_AFRL3, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRL_AFRL4, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRL_AFRL5, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRL_AFRL6, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRL_AFRL7, (AlternateFunction), (override));

	// AFRH Fields
	MOCK_METHOD(AlternateFunction, get_AFRH_AFRH8, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRH_AFRH9, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRH_AFRH10, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRH_AFRH11, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRH_AFRH12, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRH_AFRH13, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRH_AFRH14, (), (const, override));
	MOCK_METHOD(AlternateFunction, get_AFRH_AFRH15, (), (const, override));
	MOCK_METHOD(void, set_AFRH_AFRH8, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRH_AFRH9, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRH_AFRH10, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRH_AFRH11, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRH_AFRH12, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRH_AFRH13, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRH_AFRH14, (AlternateFunction), (override));
	MOCK_METHOD(void, set_AFRH_AFRH15, (AlternateFunction), (override));
};

